# name of the software
name: Sikker digital post proxyklient .NET
siteUrlText: difi.github.io/dpi-proxy-klient-dotnet

# current version of the software
version: 1.0.0
# url of the download button
downloadUrl: https://www.nuget.org/packages?q=Difi.SikkerDigitalPost.Klient

# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

#baseurl: "/sikker-digital-post-net-klient" # the subpath of your site, e.g. /blog/
baseurl: "/dpi-proxy-klient-dotnet"

##Version handling
currentCollecion: "v1_0"
currentVersion: "1.0"
versions: ["1.0"]

# Collection of versions
collections:
  v1_0:
    output: true
    permalink: /v1.0/
## End of Version handling

aboutSide: "about.html"

# list of additional links on the right of the top menu
headerLinks:
  - title: Om sikker digital post proxyklient
    url: /dpi-proxy-klient-dotnet/about.html
  - title: GitHub
    url: https://github.com/difi/dpi-proxy-klient-dotnet
  - title: Download Nuget Package
    url: https://www.nuget.org/packages?q=Difi.SikkerDigitalPost.ProxyKlient
  - title: Issues
    url: https://github.com/difi/dpi-proxy-klient-dotnet/issues

# github buttons
githubButton:
  user: difi
  repo: dpi-proxy-klient-dotnet

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-78356843-1
  domain: auto

highlight: rouge  

plugins:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

kramdown:
  input: GFM
