# name of the software
name: Sikker Digital Post .NET
siteUrlText: difi.github.io/difi-sikker-digital-post-klient-dotnet

# current version of the software
version: 3.0.1
# url of the download button
downloadUrl: https://www.nuget.org/packages?q=Difi.SikkerDigitalPost.Klient

# licence of the software
license: MIT License
licenseUrl: http://opensource.org/licenses/MIT

#baseurl: "/sikker-digital-post-net-klient" # the subpath of your site, e.g. /blog/
baseurl: "/sikker-digital-post-klient-dotnet"

##Version handling
currentCollecion: "v3_1"
currentVersion: "3.1"
versions: ["3.1", "3.0","2.0","1.6-1.11","1.5","1.4","1.3","1.2"]

# Collection of versions
collections:
  v1_2:  
    output: true
    permalink: /v1.2/
  v1_3:  
    output: true
    permalink: /v1.3/
  v1_4:  
    output: true
    permalink: /v1.4/
  v1_5:  
    output: true
    permalink: /v1.5/
  v1_6_11:  
    output: true
    permalink: /v1.6-1.11/
  v2_0:
    output: true
    permalink: /v2.0/
  v3_0:
    output: true
    permalink: /v3.0/
  v3_1:
    output: true
    permalink: /v3.1/
## End of Version handling

aboutSide: "about.html"

# list of additional links on the right of the top menu
headerLinks:
  - title: Om sikker digital post
    url: /sikker-digital-post-klient-dotnet/about.html
  - title: GitHub
    url: https://github.com/difi/sikker-digital-post-net-klient
  - title: Download Nuget Package
    url: https://www.nuget.org/packages?q=Difi.SikkerDigitalPost.Klient
  - title: Issues
    url: https://github.com/difi/sikker-digital-post-net-klient/issues

# github buttons
githubButton:
  user: difi
  repo: sikker-digital-post-klient-dotnet

# twitter buttons
twitter:
  enabled: false
  via:
  hash:
  account:

# facebook buttons
facebook:
  enabled: false
  profileUrl:

# google analytics
analytics:
  trackingid: UA-78356843-1
  domain: auto

highlight: rouge  

gems:
  - jekyll-redirect-from

exclude: ['README.md', 'Gemfile.lock', 'Gemfile']

kramdown:
  input: GFM
